format = """
[](#1B3900)\
$python\
$username\
[](bg:#1F4700 fg:#1B3900)\
$directory\
[](fg:#1F4700 bg:#417200)\
$git_branch\
$git_status\
[](fg:#417200 bg:#5FB500)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$lua\
[](fg:#5FB500 bg:#069200)\
$time\
[ ](fg:#428400)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#1B3900"
style_root = "fg:#ff0000 bg:#1B3900"
format = '[  ]($style)'

[directory]
style = "bg:#1F4700"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#5FB500"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#069200"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#5FB500"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#5FB500"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#417200"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#417200"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#5FB500"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#5FB500"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#5FB500"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#5FB500"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = ""
style = "bg:#5FB500"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#5FB500"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#5FB500"

[python]
style = "bg:#1B3900"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#5FB500"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#428400"
format = '[ $time ]($style)'
